### ISSUE TITLE
AddAttachedPicture not working as expected

### ISSUE THREAD

**Issue by stve** [bogem/id3v2#14]
I've been working on a command line utility to replace a bunch of Ruby scripts i've had to modify mp3 tags/artwork/etc and your library has made this a breeze - thanks!

All has been working great but I've been having some difficulty setting the artwork on a file. Basically, the problem i'm seeing is that there appears to be a discrepancy between `bogem/id3v2` and what taglib is showing.  Here's what i'm observing:

I have an image which I've added to my mp3 using the following code:

```go
const coverFilename string = "cover.jpg"

func addPicture() {
	filename := "Blure - Branches.mp3"

	frontCover, err := os.Open(coverFilename)
	if err != nil {
		log.Fatal("error opening cover file", err)
	}
	defer frontCover.Close()

	frontCoverBytes, err := ioutil.ReadAll(frontCover)
	if err != nil {
		log.Fatal("error reading cover file", err)
	}

	pic := id3v2.PictureFrame{
		Encoding:    id3v2.ENUTF8,
		MimeType:    "image/jpeg",
		Picture:     frontCoverBytes,
		PictureType: id3v2.PTFrontCover,
		Description: "Cover",
	}

	// Open file and find tag in it
	tag, err := id3v2.Open(filename)
	if err != nil {
		log.Fatal("error opening mp3 file", err)
	}
	defer tag.Close()

	tag.AddAttachedPicture(pic)
	if err = tag.Save(); err != nil {
		log.Fatal("Error while saving a tag:", err)
	}
}
```

As best I can tell, the attachment has been added. However, Finder (i'm on a mac) wasn't showing the cover on the file in Preview. That was my first indication that something wasn't right so I started to dig a little deeper. I made a few scripts in Ruby and Go to see what frames are included and this is where I'm seeing a difference.

Using Go:

```
Detecting MP3 files...
********************
File: Blure - Branches.mp3:
TCON
APIC
```

Using Ruby (taglib):

```
Detecting MP3 files...
********************
File: Blure - Branches.mp3
TCON
```

Using `exiftool`:

```
ExifTool Version Number         : 10.36
File Name                       : Blure - Branches.mp3
Directory                       : .
File Size                       : 7.1 MB
File Modification Date/Time     : 2017:01:06 11:08:58-05:00
File Access Date/Time           : 2017:01:06 11:09:12-05:00
File Inode Change Date/Time     : 2017:01:06 11:08:59-05:00
File Permissions                : rw-r--r--
File Type                       : MP3
File Type Extension             : mp3
MIME Type                       : audio/mpeg
MPEG Audio Version              : 1
Audio Layer                     : 3
Audio Bitrate                   : 320 kbps
Sample Rate                     : 44100
Channel Mode                    : Stereo
MS Stereo                       : Off
Intensity Stereo                : Off
Copyright Flag                  : False
Original Media                  : False
Emphasis                        : None
ID3 Size                        : 51131
Genre                           : Blues
Title                           :
Artist                          :
Album                           :
Year                            :
Comment                         :
Duration                        : 0:03:05 (approx)
```

If the file were to include an image, we'd see something like the following:

```
Picture MIME Type               : image/jpeg
Picture Type                    : Front Cover
Picture Description             : Cover
Picture                         : (Binary data 50939 bytes, use -b option to extract)
```

As you can see, the only way that I'm able to see evidence of an `APIC` frame is with my Go code. Am I doing something incorrectly when adding the picture frame? I'm fairly new to Go so it's entirely possible that this is something i'm doing incorrectly.

I created an [example repository here](https://github.com/stve/id3-issue) with pared down versions of the scripts i've been using and the files from the above examples.  Thanks!

**Comment by mro** [comment]
Hi @stve,

I add artwork like this https://github.com/mro/internet-radio-recorder/blob/master/src/enclosure-tag-cmd/tag.go#L94 and Finder©®™ loves it. As far as I can see, I just removed the 'description' (for reasons I can't remember).

Hope this helps.

**Comment by bogem** [comment]
The track initially was tagged incorrect. 
So at first you should execute this:
```go
package main

import (
	"log"

	"github.com/bogem/id3v2"
)

func main() {
	filename := "Blure - Branches.mp3"

	// Open file and find tag in it
	tag, err := id3v2.Open(filename)
	if err != nil {
		log.Fatal("error opening mp3 file", err)
	}
	defer tag.Close()

	tag.DeleteAllFrames()
	if err = tag.Save(); err != nil {
		log.Fatal("Error while saving a tag:", err)
	}
}
```
and then execute `addPicture.go`, everything will work fine:
![2017-01-07 13 38 08](https://cloud.githubusercontent.com/assets/13235519/21740558/8c5ff74e-d4de-11e6-94bf-4b45c4fe0e5a.png)

**Comment by stve** [comment]
That did the trick, thanks @bogem!
