### ISSUE TITLE
How to read a tag from a .mp3 file like "Track", "Composer" or "Comment"?

### ISSUE THREAD

**Issue by highend** [bogem/id3v2#16]
I'm slowly getting into using your library (sorry, absolute golang newbie...).

What I currently don't see:
How do I read specific tags (apart from the ones that are provided by existing methods like .Artist(), .Title(), etc.)?

E.g.:
Track (TRCK)
Comments (COMM)
or
Composer (TCOM)?
and eventually:
DISCNUMBER?

Regards,
Highend

**Comment by bogem** [comment]
Hello!
If you want to get frames, that can be only single in tag, then you should use `tag.GetLastFrame`.
E.g. getting a composer:
```go
composer := tag.GetLastFrame(tag.CommonID("Composer"))
if composer != nil {
	bpm, ok := composer.(id3v2.TextFrame)
	if !ok {
		log.Fatal("Couldn't assert composer frame")
	}
	fmt.Println(composer.Text) // Print a text from composer frame
}
```

Other information you can find in [docs](https://godoc.org/github.com/bogem/id3v2#Tag.GetFrames)

**Comment by highend** [comment]
Thanks a lot, got it so far (for Track, Composer, Comment and the CD number (Part of a set))!

There is one thing left I'd like to ask...

Is it possible to specify which kind of ID3v2.(3|4) tag will be used when the file is written with tag.Save()?
For whatever reason, some people prefer to have their files with ID3v2.3 tags instead of ID3v2.4 ones...

**Comment by bogem** [comment]
Unfortunately, id3v2 doesn't support, but if you really want it, I can implement it. It's not complicated.

Yes, I'm glad to every donation! My paypal: albertnigmatzianov@gmail.com
Thank you in advance!

**Comment by bogem** [comment]
@highend thank you very much for donation! I really appreciate it!

**Comment by highend** [comment]
This would be really nice, if you can add that!

No problem! Glad that I found your library and that I finally have a command line tool that can read & write tags with unicode characters :)

**Comment by bogem** [comment]
Don't you mind, if I add it tomorrow?

**Comment by bogem** [comment]
And actually it would be very nice, if you will open source of your CLI and upload it in GitHub. I need CLI like this but I'm a bit lazy to write it :)

**Comment by highend** [comment]
Take your time. Uh, this is my second day with the go programming language... But once I'm sure enough that it works properly I can put it on github, sure.

**Comment by bogem** [comment]
I could contribute in your cli if you need help

**Comment by bogem** [comment]
@highend done
