### ISSUE TITLE
does id3v2 work or doesn't id3v2 (commandline tool) nor iTunes get it right?

### ISSUE THREAD

**Issue by mro** [bogem/id3v2#18]
I'm confused since I found my mp3-tagger https://github.com/mro/internet-radio-recorder/tree/master/src/enclosure-tag-cmd actually doesn't write tags readable by iTunes nor http://id3v2.sourceforge.net.

I made a test over at https://github.com/mro/id3v2/commit/40e73bb7bf5c7a42d384becc8ba70a8d0e4da120 and would be super happy to hear what you think about it.

Cheers and happy 🐇

**Comment by bogem** [comment]
Thank for a bug report!
Actually I'm on my holidays (Easter in Germany) and I can't be with computer till monday (I'm writing from my iPhone). But I am testing every my commit as I use it by myself and it works for me. But are your tests passed? If not, please send me an output.

**Comment by mro** [comment]
```
time sh run.sh 

go version go1.8 darwin/amd64
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mro/gopath~"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j6/nrkx806n4pvg336kmncfncdh0000gn/T/go-build172985780=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
github.com/stretchr/testify (download)
github.com/bogem/id3v2/bwpool
github.com/bogem/id3v2/util
github.com/bogem/id3v2/rdpool
github.com/bogem/id3v2
=== RUN   TestParseHeader
--- PASS: TestParseHeader (0.00s)
=== RUN   TestWriteTagHeader
--- PASS: TestWriteTagHeader (0.00s)
=== RUN   TestUnmodified
--- PASS: TestUnmodified (0.13s)
=== RUN   TestSetArtist
--- PASS: TestSetArtist (0.24s)
=== RUN   TestSetFull
--- PASS: TestSetFull (0.23s)
=== RUN   TestParseInvalidFrameSize
--- PASS: TestParseInvalidFrameSize (0.00s)
=== RUN   TestParse
--- PASS: TestParse (0.11s)
=== RUN   TestSequenceCacheUpdate
--- PASS: TestSequenceCacheUpdate (0.00s)
=== RUN   TestSequenceCommentFramesUniqueness
--- PASS: TestSequenceCommentFramesUniqueness (0.00s)
=== RUN   TestSequencePictureFramesUniqueness
--- PASS: TestSequencePictureFramesUniqueness (0.00s)
=== RUN   TestSequenceUSLFsUniqueness
--- PASS: TestSequenceUSLFsUniqueness (0.00s)
=== RUN   TestCountLenSize
--- PASS: TestCountLenSize (0.00s)
=== RUN   TestIntegrityOfMusicAtTheBeginning
--- PASS: TestIntegrityOfMusicAtTheBeginning (0.00s)
=== RUN   TestIntegrityOfMusicAtTheEnd
--- PASS: TestIntegrityOfMusicAtTheEnd (0.06s)
=== RUN   TestCheckPermissions
--- PASS: TestCheckPermissions (0.05s)
=== RUN   TestBlankID
--- PASS: TestBlankID (0.07s)
PASS
ok  	github.com/bogem/id3v2	0.960s
?   	github.com/bogem/id3v2/bwpool	[no test files]
?   	github.com/bogem/id3v2/rdpool	[no test files]
=== RUN   TestReadTillDelim
--- PASS: TestReadTillDelim (0.00s)
=== RUN   TestReadTillZero
--- PASS: TestReadTillZero (0.00s)
=== RUN   TestNext
--- PASS: TestNext (0.00s)
=== RUN   TestReadTillDelimEOF
--- PASS: TestReadTillDelimEOF (0.00s)
=== RUN   TestReadTillDelims
--- PASS: TestReadTillDelims (0.00s)
=== RUN   TestParseSize
--- PASS: TestParseSize (0.00s)
=== RUN   TestFormSize
--- PASS: TestFormSize (0.00s)
PASS
ok  	github.com/bogem/id3v2/util	0.006s
code: 0
id3v1 tag info for /Users/mro/gopath~/src/github.com/bogem/id3v2/testdata/tmp.mp3:
Title  : love letters drenched in gasol  Artist: suicide, part 2               
Album  :                                 Year: 2015, Genre: Unknown (255)
Comment:                                 Track: 0
/Users/mro/gopath~/src/github.com/bogem/id3v2/testdata/tmp.mp3: No ID3v2 tag

real	0m10.945s
user	0m2.606s
sys	0m1.047s
```

**Comment by bogem** [comment]
Thank you for waiting and happy easter!
Actually I can't reproduce the problem.
I've executed `run.sh` and iTunes can see the tag correctly:
![2017-04-17 20 33 13](https://cloud.githubusercontent.com/assets/13235519/25099608/561dc51c-23ad-11e7-8350-e5961234d007.png)
![2017-04-17 20 34 31](https://cloud.githubusercontent.com/assets/13235519/25099612/58630602-23ad-11e7-85a1-a8f8df61aa6c.png)

But the behaviour of id3v2 cli tool is mystical for me:
1. It reads the tag (as you can see in your output, id3v2 cli shows title, artist and year), but it considers what the tag is id3v1. id3v2 library can't **physically** (there is no code) set v1 tags so I don't know, where it found this information.
2.
> Surprising is, that tmp.mp3 created by TestSetFull shows no trace of changed tags at all.

The tag is changed as you can see in my screenshots, but id3v2 cli very-very-very surprisingly for me finds completely another tag info, that even isn't set in the file. If you open the file with any hex editor (e.g. [Hex Fiend)](http://ridiculousfish.com/hexfiend/) and try to find plain words "part 2" or "love letters", you will be excited, what there are no matches. So I don't know where id3v2 cli finds this information.

**Comment by bogem** [comment]
I [deleted](https://github.com/bogem/id3v2/commit/8b94cb7d184a340cb4c022ed373b006b9a95e17e) the id3v1 tag. Update id3v2 package and try to run tests one more time. The output will be more understandable.

**Comment by mro** [comment]
wow, just tested f8f96eee26ed and works like a charm! 🐳

**Comment by mro** [comment]
hngrr, I was too fast confirming the fix. I think https://github.com/mro/id3v2/commit/eeebfe5df3fb6c4f7d11ea0f8e4c17e13f90b538 shows some issues when using a bigger mp3 (see inside `run.sh`, line 5):

* `COMM` leaks into the end of the lyrics (iTunes)
* the artwork doesn't show (iTunes)

Am curious what you think.

**Comment by bogem** [comment]
I confirm, what artwork can't be read by any tag reader (including id3v2 lib), although it's successfully written in file. I don't know why it happens, but I will figure out soon.
But I can't understand 1. and 3. points. COMM frame works as expect. And I also don't see any TENC in any mp3.

**Comment by mro** [comment]
oh, yes, sorry, you're right - the testcase provided doesn't leak COMM into lyrics but lyrics get lost altogether. Nor does it show the sticky TENC. So I'll have to re-investigate and provide a sample in case. May take a few days.

**Comment by bogem** [comment]
At first, I see, what you use "de" as language. You should choose a three-letters language code from [ISO 639-2 code list](https://www.loc.gov/standards/iso639-2/php/code_list.php) ("ger" for german language). I should write it clearer in documentation

**Comment by bogem** [comment]
Temporary solution: 
1. Use three-letters language code from as said in previous comment.
2. Set tag version to 4 (`tag.SetVersion(4)`)

iTunes will see the attached picture.
Why it doesn't work with version 3, I will figure out later.

**Comment by bogem** [comment]
id3v2.3 doesn't support the UTF-8 encoding, that's why iTunes doesn't understand UTF-8 encoding symbol and doesn't read some frames. But how does it read other text frames, like artist, title and etc, although they also use UTF-8 encoding symbol?

**Comment by mro** [comment]
maybe the meaning of bytes isn't defined by id3 at all – so it may be either ascii or utf-8 or anything else as long as writer and consumer agree. But once the lib calculates lengths, it may be fooled by 2, 3 or even more bytes per utf-8 glyph. What may cause the leak I think to have seen once.

**Comment by mro** [comment]
http://id3.org/id3v2.4.0-changes?highlight=%28utf%29

**Comment by mro** [comment]
http://id3.org/iTunes?highlight=%28utf%29

**Comment by bogem** [comment]
> But once the lib calculates lengths, it may be fooled by 2, 3 or even more bytes per utf-8 glyph. 

No, it's not the reason of this problem. id3v2 lib calculates length as `len(text)` and len function counts bytes in text.

**Comment by bogem** [comment]
The problem is, what there is no good encoding converter for Golang. The only option is [github.com/djimenez/iconv-go](https://github.com/djimenez/iconv-go), but it just C bindings to iconv library. I could integrate it to id3v2 library and automatically convert encodings by parsing and writing, but I don't want to make library complex. If user needs other encoding, he/she should converts encodings manually.

**Comment by mro** [comment]
ic, doing the encoding isn't necessarily task for this lib here, maybe just point the requirements out in either the docs or the names (`FooBarUTF16LE`)?

And having v4 at hand for UTF8 is fine for me.

**Comment by mro** [comment]
Thanks a lot for this nice lib, your help and your kindness.

**Comment by bogem** [comment]
> maybe just point the requirements out in either the docs or the names (FooBarUTF16LE)?

Actually I have no idea, how I should handle this issue now. So I just decided to wait for issue from users, who really needs other encodings.

You're always welcome! Thank you for your bug reports! I'm always glad to help with problems of id3v2 :)
