### ISSUE TITLE
add COMM and USLT

### ISSUE THREAD

**Issue by mro** [bogem/id3v2#3]
you mentioned to add frames on request. For my internet recorder, I add the radio broadcast abstract [both into `COMM` and `USLT`](https://github.com/mro/internet-radio-recorder/blob/master/htdocs/app/enclosure-tag.rb#L86). In order to reduce the technology mix a bit and get rid of ruby it would be really neat to have [a Go option](https://github.com/mro/internet-radio-recorder/issues/30).

Would you mind enabling them?

**Comment by bogem** [comment]
Ok, I will enable it either today or tomorrow

**Comment by mro** [comment]
no hurries. I may use it somewhen in the next months.

**Comment by bogem** [comment]
Anyway, I have nothing to do😅
So it will be realized soon

**Comment by bogem** [comment]
I added USLT and COMM frames. Instructions you can see in README. And please prove the work of these frames🙏

**Comment by mro** [comment]
I didn't forget about to test this, it will just still take some time.

**Comment by bogem** [comment]
Good :)
There was one more update: I added documentation. Can you say, do you find it convenient to read?

**Comment by mro** [comment]
I just did a `$ go get -u github.com/bogem/id3v2` and took a look at USLT and COMM. USLT makes it perfectly into iTunes while COMM doesn't show up – but that may well be a iTunes quirk.

So: I'm happy, thanks a lot for this lean library and thanks for your patience!

**Comment by mro** [comment]
btw. that's exactly the same with the ruby/c++ taglib approach in https://github.com/bogem/id3v2/issues/3#issue-157374256

**Comment by mro** [comment]
>  I added documentation. Can you say, do you find it convenient to read?

I'm maybe an unusual documentation-reader, I prefer it as lean as your library :-) The fewer, the better. Where I took how to use it, is the tests. They're all I care about, thanks a lot again!

**Comment by bogem** [comment]
My iTunes also doesn't see COMM frames. I hope, it's not because my lib doesn't work well 😂
Anyway, thanks for your offers! I'm always glad to hear new ones :)

**Comment by mro** [comment]
your lib is awesome, iTunes is a shame.

**Comment by bogem** [comment]
Thank you! Very nice to hear😌
