### ISSUE TITLE
tag.AddAttachedPicture() not working

### ISSUE THREAD

**Issue by kalbhor** [bogem/id3v2#31]
The album art doesn't seem to get added in the music file. Here ```path``` is a valid mp3 file and ```metadata.Image``` is a valid jpeg image byte array. 

```
	tag, err := id3v2.Open(path, id3v2.Options{Parse: true})
	checkErr(err)
	defer tag.Close()

	pic := id3v2.PictureFrame{
		Encoding:    id3v2.EncodingUTF8,
		MimeType:    "image/jpeg",
		PictureType: id3v2.PTFrontCover,
		Description: "Front cover",
		Picture:     metadata.Image,
	}
	tag.AddAttachedPicture(pic)
	if err = tag.Save(); err != nil {
		log.Fatal("Error : ", err)
	}
```

**Comment by kalbhor** [comment]
Found the problem. Turns out there's a problem with MacOS High Sierra, and it sometimes fails to show album covers in Finder. 

Sorry for raising this issue. Its not related to your program.

**Comment by bogem** [comment]
@kalbhor Sometimes I encounter this issue too. It's better to check ID3 tags in iTunes.
