### ISSUE TITLE
Add support for `SetTrack`

### ISSUE THREAD

**Issue by dimuls** [bogem/id3v2#38]
You have nice library, but i miss `SetTrack` method to set track number. Can you implement it please?

**Comment by dimuls** [comment]
This works as expected:
```go
mp3.AddFrame(trackFrameID, id3v2.TextFrame{Encoding: id3v2.EncodingUTF8,
	Text: fmt.Sprintf("%d/%d", t.Number, len(a.Tracks))})
```
Issue can be close, but consider to add `SetTrack`. Thank you!

**Comment by bogem** [comment]
I will not add `SetTrack` method, because it's pretty rarely used. I will keep methods only for artist, album and year.

But I added a convenience method for adding text frames in 7e43476:
```go
tag.AddTextFrame(tag.CommonID("Track number/Position in set"), tag.DefaultEncoding(), fmt.Sprintf("%d/%d", t.Number, len(a.Tracks))}))
```
