### ISSUE TITLE
null byte in tags

### ISSUE THREAD

**Issue by jypelle** [bogem/id3v2#41]
When using `id3v2.ParseReader(reader, id3v2.Options{Parse: true})` on (all?) mp3 downloaded from https://www.jamendo.com, extracted artist, album, title, ... contains a null byte at the end of the string.

I'm using `strings.TrimRight(s,"\x00")` as a workaround but I think that should be done inside id3v2.decodeText

**Comment by bogem** [comment]
I don't know if it's jamendo's issues or mine, but I don't think that each text in tag should be terminated with `$00 (00)`. It's also not 100% clear from spec. But anyway I'll add trim.

**Comment by bogem** [comment]
Reminder for me: Add tests

**Comment by bogem** [comment]
Also see https://github.com/bogem/id3v2/pull/33
