### ISSUE TITLE
Doesn't add PictureFrame to ogg formats!

### ISSUE THREAD

**Issue by AYehia0** [bogem/id3v2#80]
Thanks for the great package.
It just works for all mp3 files, but when it comes to different formats, like `ogg` it adds everything except the `PictureFrame`, which is kinda weird.

```golang
...
	if imgBytes != nil {
		tag.AddAttachedPicture(
			id3v2.PictureFrame{
				Encoding:    id3v2.EncodingUTF8,
				MimeType:    "image/jpeg",
				Picture:     imgBytes,
				Description: track.SoundData.Description, // well, coz why not :D
			},
		)
	}
...
```

**Comment by bogem** [comment]
Hey @AYehia0! Thanks a lot for reporting this issue! 
Can you please send an OGG file where I can reproduce the issue?

**Comment by AYehia0** [comment]
Thanks @bogem, I have tested the OGG/OPUS file and I found out that the issue is within the audio player itself, not the package :smile: 
Thank you for this great package, keep it up :D
