### ISSUE TITLE
Temp file gets created, and if issue occurs, never gets cleaned up

### ISSUE THREAD

**Issue by gabek** [bogem/id3v2#9]
I just noticed a bunch of random files in /tmp.  They had randomly generated names so I couldn't tell what they were from.  Digging deeper I found they were audio files, but I didn't know how they got there.

Looking through the different possibilities I came upon https://github.com/bogem/id3v2/blob/master/tag.go#L225.  It seems to make sense.  I've seen some tagging errors happen over time, and my guess is each time I have an error tagging with id3v2 it leaves that temp file.

Would this be the case?

**Comment by bogem** [comment]
Which OS do you use?
On macOS I haven't got any audio files in temporary directory, because [this line](https://github.com/bogem/id3v2/blob/master/tag.go#L265) should move `newFile` from temporary directory to the directory of original file:

> func Rename(oldpath, newpath string) error
    Rename renames (moves) oldpath to newpath. If newpath already exists,
    Rename replaces it.
